/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_nassimwindow (void);
GtkWidget* create_ajoutnassim (void);
GtkWidget* create_modifiernassim (void);
GtkWidget* create_supprimerwindow (void);
GtkWidget* create_youssefwindow (void);
GtkWidget* create_ajoutyoussef (void);
GtkWidget* create_modifieryoussef (void);
GtkWidget* create_supprimeryoussef (void);
GtkWidget* create_salmawindow (void);
GtkWidget* create_ajoutsalma (void);
GtkWidget* create_modifiersalma (void);
GtkWidget* create_supprimersalma (void);
GtkWidget* create_mariemwindow (void);
GtkWidget* create_ajoutmariem (void);
GtkWidget* create_modifiermariem (void);
GtkWidget* create_supprimermariem (void);
GtkWidget* create_affichage (void);
GtkWidget* create_pourcentagedemande (void);
GtkWidget* create_daliwindow (void);
GtkWidget* create_ajoutdali (void);
GtkWidget* create_modifierdali (void);
GtkWidget* create_supprimerwindow (void);
GtkWidget* create_omarwindow (void);
GtkWidget* create_ajoutomar (void);
GtkWidget* create_modifieromar (void);
GtkWidget* create_supprimeromar (void);
GtkWidget* create_gestionwindow (void);
GtkWidget* create_loginwindow (void);
GtkWidget* create_cherchernassim (void);
