/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_nassimwindow (void)
{
  GtkWidget *nassimwindow;
  GtkWidget *fixed1;
  GtkWidget *treeview1;
  GtkWidget *button1;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label1;
  GtkWidget *button3;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label3;
  GtkWidget *button2;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label2;
  GtkWidget *button4;

  nassimwindow = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (nassimwindow), _("nassimwindow"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (nassimwindow), fixed1);
  gtk_widget_set_size_request (fixed1, 800, 600);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed1), treeview1, 0, 72);
  gtk_widget_set_size_request (treeview1, 800, 200);

  button1 = gtk_button_new ();
  gtk_widget_show (button1);
  gtk_fixed_put (GTK_FIXED (fixed1), button1, 136, 376);
  gtk_widget_set_size_request (button1, 110, 29);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (button1), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label1 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label1);
  gtk_box_pack_start (GTK_BOX (hbox1), label1, FALSE, FALSE, 0);

  button3 = gtk_button_new ();
  gtk_widget_show (button3);
  gtk_fixed_put (GTK_FIXED (fixed1), button3, 136, 424);
  gtk_widget_set_size_request (button3, 110, 29);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (button3), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label3 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (hbox3), label3, FALSE, FALSE, 0);

  button2 = gtk_button_new ();
  gtk_widget_show (button2);
  gtk_fixed_put (GTK_FIXED (fixed1), button2, 448, 376);
  gtk_widget_set_size_request (button2, 110, 29);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (button2), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label2 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label2);
  gtk_box_pack_start (GTK_BOX (hbox2), label2, FALSE, FALSE, 0);

  button4 = gtk_button_new_with_mnemonic (_("%utilisateur"));
  gtk_widget_show (button4);
  gtk_fixed_put (GTK_FIXED (fixed1), button4, 448, 416);
  gtk_widget_set_size_request (button4, 110, 29);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (nassimwindow, nassimwindow, "nassimwindow");
  GLADE_HOOKUP_OBJECT (nassimwindow, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (nassimwindow, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (nassimwindow, button1, "button1");
  GLADE_HOOKUP_OBJECT (nassimwindow, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (nassimwindow, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (nassimwindow, image1, "image1");
  GLADE_HOOKUP_OBJECT (nassimwindow, label1, "label1");
  GLADE_HOOKUP_OBJECT (nassimwindow, button3, "button3");
  GLADE_HOOKUP_OBJECT (nassimwindow, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (nassimwindow, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (nassimwindow, image3, "image3");
  GLADE_HOOKUP_OBJECT (nassimwindow, label3, "label3");
  GLADE_HOOKUP_OBJECT (nassimwindow, button2, "button2");
  GLADE_HOOKUP_OBJECT (nassimwindow, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (nassimwindow, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (nassimwindow, image2, "image2");
  GLADE_HOOKUP_OBJECT (nassimwindow, label2, "label2");
  GLADE_HOOKUP_OBJECT (nassimwindow, button4, "button4");

  return nassimwindow;
}

GtkWidget*
create_ajoutnassim (void)
{
  GtkWidget *ajoutnassim;
  GtkWidget *fixed2;
  GtkWidget *entry1;
  GtkWidget *entry2;
  GtkWidget *entry3;
  GtkWidget *entry4;
  GtkWidget *radiobutton1;
  GSList *radiobutton1_group = NULL;
  GtkWidget *radiobutton2;
  GtkWidget *comboboxentry1;
  GtkWidget *label9;
  GtkWidget *label10;
  GtkWidget *button6;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label11;
  GtkWidget *button5;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label12;
  GtkWidget *label8;
  GtkWidget *label4;
  GtkWidget *label5;
  GtkWidget *label6;
  GtkWidget *label7;

  ajoutnassim = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ajoutnassim), _("ajoutnassim"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (ajoutnassim), fixed2);
  gtk_widget_set_size_request (fixed2, 800, 600);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_fixed_put (GTK_FIXED (fixed2), entry1, 264, 112);
  gtk_widget_set_size_request (entry1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 8226);

  entry2 = gtk_entry_new ();
  gtk_widget_show (entry2);
  gtk_fixed_put (GTK_FIXED (fixed2), entry2, 264, 152);
  gtk_widget_set_size_request (entry2, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2), 8226);

  entry3 = gtk_entry_new ();
  gtk_widget_show (entry3);
  gtk_fixed_put (GTK_FIXED (fixed2), entry3, 264, 192);
  gtk_widget_set_size_request (entry3, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3), 8226);

  entry4 = gtk_entry_new ();
  gtk_widget_show (entry4);
  gtk_fixed_put (GTK_FIXED (fixed2), entry4, 264, 232);
  gtk_widget_set_size_request (entry4, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry4), 8226);

  radiobutton1 = gtk_radio_button_new_with_mnemonic (NULL, _("Homme"));
  gtk_widget_show (radiobutton1);
  gtk_fixed_put (GTK_FIXED (fixed2), radiobutton1, 256, 272);
  gtk_widget_set_size_request (radiobutton1, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton1), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton1));

  radiobutton2 = gtk_radio_button_new_with_mnemonic (NULL, _("Femme"));
  gtk_widget_show (radiobutton2);
  gtk_fixed_put (GTK_FIXED (fixed2), radiobutton2, 256, 304);
  gtk_widget_set_size_request (radiobutton2, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton2), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton2));

  comboboxentry1 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry1);
  gtk_fixed_put (GTK_FIXED (fixed2), comboboxentry1, 264, 344);
  gtk_widget_set_size_request (comboboxentry1, 189, 29);

  label9 = gtk_label_new (_("<span ><b> Sexe : </b></span>"));
  gtk_widget_show (label9);
  gtk_fixed_put (GTK_FIXED (fixed2), label9, 144, 272);
  gtk_widget_set_size_request (label9, 64, 17);
  gtk_label_set_use_markup (GTK_LABEL (label9), TRUE);

  label10 = gtk_label_new (_("<span ><b> Role : </b></span>"));
  gtk_widget_show (label10);
  gtk_fixed_put (GTK_FIXED (fixed2), label10, 152, 352);
  gtk_widget_set_size_request (label10, 49, 17);
  gtk_label_set_use_markup (GTK_LABEL (label10), TRUE);

  button6 = gtk_button_new ();
  gtk_widget_show (button6);
  gtk_fixed_put (GTK_FIXED (fixed2), button6, 464, 408);
  gtk_widget_set_size_request (button6, 110, 29);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (button6), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label11 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label11);
  gtk_box_pack_start (GTK_BOX (hbox4), label11, FALSE, FALSE, 0);

  button5 = gtk_button_new ();
  gtk_widget_show (button5);
  gtk_fixed_put (GTK_FIXED (fixed2), button5, 0, 0);
  gtk_widget_set_size_request (button5, 110, 29);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (button5), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label12 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label12);
  gtk_box_pack_start (GTK_BOX (hbox5), label12, FALSE, FALSE, 0);

  label8 = gtk_label_new (_("<span ><b> ID : </b></span>"));
  gtk_widget_show (label8);
  gtk_fixed_put (GTK_FIXED (fixed2), label8, 144, 240);
  gtk_widget_set_size_request (label8, 41, 17);
  gtk_label_set_use_markup (GTK_LABEL (label8), TRUE);

  label4 = gtk_label_new (_("<span foreground=\"RED\" ><b> Ajout utilisateur: </b></span>"));
  gtk_widget_show (label4);
  gtk_fixed_put (GTK_FIXED (fixed2), label4, 344, 48);
  gtk_widget_set_size_request (label4, 176, 25);
  gtk_label_set_use_markup (GTK_LABEL (label4), TRUE);

  label5 = gtk_label_new (_("<span ><b> Nom: </b></span>"));
  gtk_widget_show (label5);
  gtk_fixed_put (GTK_FIXED (fixed2), label5, 144, 112);
  gtk_widget_set_size_request (label5, 41, 17);
  gtk_label_set_use_markup (GTK_LABEL (label5), TRUE);

  label6 = gtk_label_new (_("<span ><b> Prenom: </b></span>"));
  gtk_widget_show (label6);
  gtk_fixed_put (GTK_FIXED (fixed2), label6, 144, 152);
  gtk_widget_set_size_request (label6, 72, 17);
  gtk_label_set_use_markup (GTK_LABEL (label6), TRUE);

  label7 = gtk_label_new (_("<span ><b> Mot de passe : </b></span>"));
  gtk_widget_show (label7);
  gtk_fixed_put (GTK_FIXED (fixed2), label7, 144, 192);
  gtk_widget_set_size_request (label7, 112, 17);
  gtk_label_set_use_markup (GTK_LABEL (label7), TRUE);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ajoutnassim, ajoutnassim, "ajoutnassim");
  GLADE_HOOKUP_OBJECT (ajoutnassim, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (ajoutnassim, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (ajoutnassim, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (ajoutnassim, entry3, "entry3");
  GLADE_HOOKUP_OBJECT (ajoutnassim, entry4, "entry4");
  GLADE_HOOKUP_OBJECT (ajoutnassim, radiobutton1, "radiobutton1");
  GLADE_HOOKUP_OBJECT (ajoutnassim, radiobutton2, "radiobutton2");
  GLADE_HOOKUP_OBJECT (ajoutnassim, comboboxentry1, "comboboxentry1");
  GLADE_HOOKUP_OBJECT (ajoutnassim, label9, "label9");
  GLADE_HOOKUP_OBJECT (ajoutnassim, label10, "label10");
  GLADE_HOOKUP_OBJECT (ajoutnassim, button6, "button6");
  GLADE_HOOKUP_OBJECT (ajoutnassim, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (ajoutnassim, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (ajoutnassim, image4, "image4");
  GLADE_HOOKUP_OBJECT (ajoutnassim, label11, "label11");
  GLADE_HOOKUP_OBJECT (ajoutnassim, button5, "button5");
  GLADE_HOOKUP_OBJECT (ajoutnassim, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (ajoutnassim, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (ajoutnassim, image5, "image5");
  GLADE_HOOKUP_OBJECT (ajoutnassim, label12, "label12");
  GLADE_HOOKUP_OBJECT (ajoutnassim, label8, "label8");
  GLADE_HOOKUP_OBJECT (ajoutnassim, label4, "label4");
  GLADE_HOOKUP_OBJECT (ajoutnassim, label5, "label5");
  GLADE_HOOKUP_OBJECT (ajoutnassim, label6, "label6");
  GLADE_HOOKUP_OBJECT (ajoutnassim, label7, "label7");

  return ajoutnassim;
}

GtkWidget*
create_modifiernassim (void)
{
  GtkWidget *modifiernassim;
  GtkWidget *fixed3;
  GtkWidget *entry5;
  GtkWidget *entry6;
  GtkWidget *entry7;
  GtkWidget *entry8;
  GtkWidget *radiobutton4;
  GSList *radiobutton4_group = NULL;
  GtkWidget *comboboxentry2;
  GtkWidget *label14;
  GtkWidget *label15;
  GtkWidget *radiobutton3;
  GtkWidget *label16;
  GtkWidget *label17;
  GtkWidget *label18;
  GtkWidget *label19;
  GtkWidget *label13;
  GtkWidget *button8;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label20;
  GtkWidget *button7;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label21;

  modifiernassim = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (modifiernassim), _("modifiernassim"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (modifiernassim), fixed3);
  gtk_widget_set_size_request (fixed3, 800, 600);

  entry5 = gtk_entry_new ();
  gtk_widget_show (entry5);
  gtk_fixed_put (GTK_FIXED (fixed3), entry5, 264, 104);
  gtk_widget_set_size_request (entry5, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry5), 8226);

  entry6 = gtk_entry_new ();
  gtk_widget_show (entry6);
  gtk_fixed_put (GTK_FIXED (fixed3), entry6, 264, 144);
  gtk_widget_set_size_request (entry6, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry6), 8226);

  entry7 = gtk_entry_new ();
  gtk_widget_show (entry7);
  gtk_fixed_put (GTK_FIXED (fixed3), entry7, 264, 184);
  gtk_widget_set_size_request (entry7, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry7), 8226);

  entry8 = gtk_entry_new ();
  gtk_widget_show (entry8);
  gtk_fixed_put (GTK_FIXED (fixed3), entry8, 264, 224);
  gtk_widget_set_size_request (entry8, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry8), 8226);

  radiobutton4 = gtk_radio_button_new_with_mnemonic (NULL, _("radiobutton4"));
  gtk_widget_show (radiobutton4);
  gtk_fixed_put (GTK_FIXED (fixed3), radiobutton4, 256, 312);
  gtk_widget_set_size_request (radiobutton4, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton4), radiobutton4_group);
  radiobutton4_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton4));

  comboboxentry2 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry2);
  gtk_fixed_put (GTK_FIXED (fixed3), comboboxentry2, 264, 352);
  gtk_widget_set_size_request (comboboxentry2, 189, 29);

  label14 = gtk_label_new (_("<span ><b> Nom: </b></span>"));
  gtk_widget_show (label14);
  gtk_fixed_put (GTK_FIXED (fixed3), label14, 128, 104);
  gtk_widget_set_size_request (label14, 49, 17);
  gtk_label_set_use_markup (GTK_LABEL (label14), TRUE);

  label15 = gtk_label_new (_("<span ><b> Prenom : </b></span>"));
  gtk_widget_show (label15);
  gtk_fixed_put (GTK_FIXED (fixed3), label15, 128, 144);
  gtk_widget_set_size_request (label15, 72, 25);
  gtk_label_set_use_markup (GTK_LABEL (label15), TRUE);

  radiobutton3 = gtk_radio_button_new_with_mnemonic (NULL, _("radiobutton3"));
  gtk_widget_show (radiobutton3);
  gtk_fixed_put (GTK_FIXED (fixed3), radiobutton3, 256, 280);
  gtk_widget_set_size_request (radiobutton3, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton3), radiobutton4_group);
  radiobutton4_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton3));

  label16 = gtk_label_new (_("<span ><b> Mot de passe : </b></span>"));
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (fixed3), label16, 128, 184);
  gtk_widget_set_size_request (label16, 112, 25);
  gtk_label_set_use_markup (GTK_LABEL (label16), TRUE);

  label17 = gtk_label_new (_("<span ><b> ID : </b></span>"));
  gtk_widget_show (label17);
  gtk_fixed_put (GTK_FIXED (fixed3), label17, 120, 232);
  gtk_widget_set_size_request (label17, 49, 17);
  gtk_label_set_use_markup (GTK_LABEL (label17), TRUE);

  label18 = gtk_label_new (_("<span ><b> Sexe : </b></span>"));
  gtk_widget_show (label18);
  gtk_fixed_put (GTK_FIXED (fixed3), label18, 128, 280);
  gtk_widget_set_size_request (label18, 56, 16);
  gtk_label_set_use_markup (GTK_LABEL (label18), TRUE);

  label19 = gtk_label_new (_("<span ><b> Role : </b></span>"));
  gtk_widget_show (label19);
  gtk_fixed_put (GTK_FIXED (fixed3), label19, 120, 352);
  gtk_widget_set_size_request (label19, 72, 17);
  gtk_label_set_use_markup (GTK_LABEL (label19), TRUE);

  label13 = gtk_label_new (_("<span foreground=\"RED\" ><b> Modifier utilisateur: </b></span>"));
  gtk_widget_show (label13);
  gtk_fixed_put (GTK_FIXED (fixed3), label13, 328, 24);
  gtk_widget_set_size_request (label13, 184, 33);
  gtk_label_set_use_markup (GTK_LABEL (label13), TRUE);

  button8 = gtk_button_new ();
  gtk_widget_show (button8);
  gtk_fixed_put (GTK_FIXED (fixed3), button8, 472, 424);
  gtk_widget_set_size_request (button8, 110, 29);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (button8), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label20 = gtk_label_new_with_mnemonic (_("Confirmer"));
  gtk_widget_show (label20);
  gtk_box_pack_start (GTK_BOX (hbox6), label20, FALSE, FALSE, 0);

  button7 = gtk_button_new ();
  gtk_widget_show (button7);
  gtk_fixed_put (GTK_FIXED (fixed3), button7, 0, 0);
  gtk_widget_set_size_request (button7, 110, 29);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (button7), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label21 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label21);
  gtk_box_pack_start (GTK_BOX (hbox7), label21, FALSE, FALSE, 0);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (modifiernassim, modifiernassim, "modifiernassim");
  GLADE_HOOKUP_OBJECT (modifiernassim, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (modifiernassim, entry5, "entry5");
  GLADE_HOOKUP_OBJECT (modifiernassim, entry6, "entry6");
  GLADE_HOOKUP_OBJECT (modifiernassim, entry7, "entry7");
  GLADE_HOOKUP_OBJECT (modifiernassim, entry8, "entry8");
  GLADE_HOOKUP_OBJECT (modifiernassim, radiobutton4, "radiobutton4");
  GLADE_HOOKUP_OBJECT (modifiernassim, comboboxentry2, "comboboxentry2");
  GLADE_HOOKUP_OBJECT (modifiernassim, label14, "label14");
  GLADE_HOOKUP_OBJECT (modifiernassim, label15, "label15");
  GLADE_HOOKUP_OBJECT (modifiernassim, radiobutton3, "radiobutton3");
  GLADE_HOOKUP_OBJECT (modifiernassim, label16, "label16");
  GLADE_HOOKUP_OBJECT (modifiernassim, label17, "label17");
  GLADE_HOOKUP_OBJECT (modifiernassim, label18, "label18");
  GLADE_HOOKUP_OBJECT (modifiernassim, label19, "label19");
  GLADE_HOOKUP_OBJECT (modifiernassim, label13, "label13");
  GLADE_HOOKUP_OBJECT (modifiernassim, button8, "button8");
  GLADE_HOOKUP_OBJECT (modifiernassim, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (modifiernassim, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (modifiernassim, image6, "image6");
  GLADE_HOOKUP_OBJECT (modifiernassim, label20, "label20");
  GLADE_HOOKUP_OBJECT (modifiernassim, button7, "button7");
  GLADE_HOOKUP_OBJECT (modifiernassim, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (modifiernassim, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (modifiernassim, image7, "image7");
  GLADE_HOOKUP_OBJECT (modifiernassim, label21, "label21");

  return modifiernassim;
}

GtkWidget*
create_supprimerwindow (void)
{
  GtkWidget *supprimerwindow;
  GtkWidget *fixed4;
  GtkWidget *entry9;
  GtkWidget *label22;
  GtkWidget *label23;
  GtkWidget *button10;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label24;
  GtkWidget *button9;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image9;
  GtkWidget *label25;

  supprimerwindow = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (supprimerwindow), _("supprimerwindow"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (supprimerwindow), fixed4);

  entry9 = gtk_entry_new ();
  gtk_widget_show (entry9);
  gtk_fixed_put (GTK_FIXED (fixed4), entry9, 160, 96);
  gtk_widget_set_size_request (entry9, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry9), 8226);

  label22 = gtk_label_new (_("<span foreground=\"RED\" ><b> Supprimer utilisateur: </b></span>"));
  gtk_widget_show (label22);
  gtk_fixed_put (GTK_FIXED (fixed4), label22, 128, 32);
  gtk_widget_set_size_request (label22, 200, 17);
  gtk_label_set_use_markup (GTK_LABEL (label22), TRUE);

  label23 = gtk_label_new (_("<span ><b> ID : </b></span>"));
  gtk_widget_show (label23);
  gtk_fixed_put (GTK_FIXED (fixed4), label23, 104, 104);
  gtk_widget_set_size_request (label23, 49, 17);
  gtk_label_set_use_markup (GTK_LABEL (label23), TRUE);

  button10 = gtk_button_new ();
  gtk_widget_show (button10);
  gtk_fixed_put (GTK_FIXED (fixed4), button10, 264, 176);
  gtk_widget_set_size_request (button10, 110, 29);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (button10), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  label24 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label24);
  gtk_box_pack_start (GTK_BOX (hbox8), label24, FALSE, FALSE, 0);

  button9 = gtk_button_new ();
  gtk_widget_show (button9);
  gtk_fixed_put (GTK_FIXED (fixed4), button9, 0, 0);
  gtk_widget_set_size_request (button9, 110, 29);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (button9), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image9 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox9), image9, FALSE, FALSE, 0);

  label25 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label25);
  gtk_box_pack_start (GTK_BOX (hbox9), label25, FALSE, FALSE, 0);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (supprimerwindow, supprimerwindow, "supprimerwindow");
  GLADE_HOOKUP_OBJECT (supprimerwindow, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (supprimerwindow, entry9, "entry9");
  GLADE_HOOKUP_OBJECT (supprimerwindow, label22, "label22");
  GLADE_HOOKUP_OBJECT (supprimerwindow, label23, "label23");
  GLADE_HOOKUP_OBJECT (supprimerwindow, button10, "button10");
  GLADE_HOOKUP_OBJECT (supprimerwindow, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (supprimerwindow, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (supprimerwindow, image8, "image8");
  GLADE_HOOKUP_OBJECT (supprimerwindow, label24, "label24");
  GLADE_HOOKUP_OBJECT (supprimerwindow, button9, "button9");
  GLADE_HOOKUP_OBJECT (supprimerwindow, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (supprimerwindow, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (supprimerwindow, image9, "image9");
  GLADE_HOOKUP_OBJECT (supprimerwindow, label25, "label25");

  return supprimerwindow;
}

GtkWidget*
create_youssefwindow (void)
{
  GtkWidget *youssefwindow;
  GtkWidget *fixed5;
  GtkWidget *treeview2;
  GtkWidget *button11;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image10;
  GtkWidget *label26;
  GtkWidget *button12;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image11;
  GtkWidget *label27;
  GtkWidget *button13;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image12;
  GtkWidget *label28;

  youssefwindow = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (youssefwindow), _("youssefwindow"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (youssefwindow), fixed5);

  treeview2 = gtk_tree_view_new ();
  gtk_widget_show (treeview2);
  gtk_fixed_put (GTK_FIXED (fixed5), treeview2, 0, 72);
  gtk_widget_set_size_request (treeview2, 800, 200);

  button11 = gtk_button_new ();
  gtk_widget_show (button11);
  gtk_fixed_put (GTK_FIXED (fixed5), button11, 152, 392);
  gtk_widget_set_size_request (button11, 110, 29);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (button11), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image10 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox10), image10, FALSE, FALSE, 0);

  label26 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label26);
  gtk_box_pack_start (GTK_BOX (hbox10), label26, FALSE, FALSE, 0);

  button12 = gtk_button_new ();
  gtk_widget_show (button12);
  gtk_fixed_put (GTK_FIXED (fixed5), button12, 328, 392);
  gtk_widget_set_size_request (button12, 110, 29);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (button12), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image11 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox11), image11, FALSE, FALSE, 0);

  label27 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label27);
  gtk_box_pack_start (GTK_BOX (hbox11), label27, FALSE, FALSE, 0);

  button13 = gtk_button_new ();
  gtk_widget_show (button13);
  gtk_fixed_put (GTK_FIXED (fixed5), button13, 520, 392);
  gtk_widget_set_size_request (button13, 110, 29);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (button13), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image12 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox12), image12, FALSE, FALSE, 0);

  label28 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label28);
  gtk_box_pack_start (GTK_BOX (hbox12), label28, FALSE, FALSE, 0);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (youssefwindow, youssefwindow, "youssefwindow");
  GLADE_HOOKUP_OBJECT (youssefwindow, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (youssefwindow, treeview2, "treeview2");
  GLADE_HOOKUP_OBJECT (youssefwindow, button11, "button11");
  GLADE_HOOKUP_OBJECT (youssefwindow, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (youssefwindow, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (youssefwindow, image10, "image10");
  GLADE_HOOKUP_OBJECT (youssefwindow, label26, "label26");
  GLADE_HOOKUP_OBJECT (youssefwindow, button12, "button12");
  GLADE_HOOKUP_OBJECT (youssefwindow, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (youssefwindow, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (youssefwindow, image11, "image11");
  GLADE_HOOKUP_OBJECT (youssefwindow, label27, "label27");
  GLADE_HOOKUP_OBJECT (youssefwindow, button13, "button13");
  GLADE_HOOKUP_OBJECT (youssefwindow, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (youssefwindow, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (youssefwindow, image12, "image12");
  GLADE_HOOKUP_OBJECT (youssefwindow, label28, "label28");

  return youssefwindow;
}

GtkWidget*
create_ajoutyoussef (void)
{
  GtkWidget *ajoutyoussef;
  GtkWidget *fixed6;
  GtkWidget *entry10;
  GtkWidget *entry11;
  GtkWidget *entry12;
  GtkObject *spinbutton1_adj;
  GtkWidget *spinbutton1;
  GtkObject *spinbutton2_adj;
  GtkWidget *spinbutton2;
  GtkObject *spinbutton3_adj;
  GtkWidget *spinbutton3;
  GtkWidget *label34;
  GtkWidget *label35;
  GtkWidget *label36;
  GtkWidget *button14;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image14;
  GtkWidget *label38;
  GtkWidget *label29;
  GtkWidget *label33;
  GtkWidget *label31;
  GtkWidget *label30;
  GtkWidget *label32;
  GtkWidget *label39;
  GtkWidget *button15;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image13;
  GtkWidget *label37;
  GtkWidget *comboboxentry3;
  GtkWidget *label49;
  GtkWidget *radiobutton5;
  GSList *radiobutton5_group = NULL;
  GtkWidget *radiobutton6;

  ajoutyoussef = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (ajoutyoussef, 800, 600);
  gtk_window_set_title (GTK_WINDOW (ajoutyoussef), _("ajoutyoussef"));

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (ajoutyoussef), fixed6);

  entry10 = gtk_entry_new ();
  gtk_widget_show (entry10);
  gtk_fixed_put (GTK_FIXED (fixed6), entry10, 288, 104);
  gtk_widget_set_size_request (entry10, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry10), 8226);

  entry11 = gtk_entry_new ();
  gtk_widget_show (entry11);
  gtk_fixed_put (GTK_FIXED (fixed6), entry11, 288, 152);
  gtk_widget_set_size_request (entry11, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry11), 8226);

  entry12 = gtk_entry_new ();
  gtk_widget_show (entry12);
  gtk_fixed_put (GTK_FIXED (fixed6), entry12, 288, 200);
  gtk_widget_set_size_request (entry12, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry12), 8226);

  spinbutton1_adj = gtk_adjustment_new (7, 1, 31, 1, 10, 10);
  spinbutton1 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1_adj), 1, 0);
  gtk_widget_show (spinbutton1);
  gtk_fixed_put (GTK_FIXED (fixed6), spinbutton1, 288, 296);
  gtk_widget_set_size_request (spinbutton1, 60, 27);

  spinbutton2_adj = gtk_adjustment_new (11, 1, 12, 1, 10, 10);
  spinbutton2 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton2_adj), 1, 0);
  gtk_widget_show (spinbutton2);
  gtk_fixed_put (GTK_FIXED (fixed6), spinbutton2, 384, 296);
  gtk_widget_set_size_request (spinbutton2, 60, 27);

  spinbutton3_adj = gtk_adjustment_new (2023, 1970, 2005, 1, 10, 10);
  spinbutton3 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton3_adj), 1, 0);
  gtk_widget_show (spinbutton3);
  gtk_fixed_put (GTK_FIXED (fixed6), spinbutton3, 488, 296);
  gtk_widget_set_size_request (spinbutton3, 60, 27);

  label34 = gtk_label_new (_("Jour :"));
  gtk_widget_show (label34);
  gtk_fixed_put (GTK_FIXED (fixed6), label34, 288, 264);
  gtk_widget_set_size_request (label34, 49, 17);

  label35 = gtk_label_new (_("Mois :"));
  gtk_widget_show (label35);
  gtk_fixed_put (GTK_FIXED (fixed6), label35, 392, 264);
  gtk_widget_set_size_request (label35, 49, 17);

  label36 = gtk_label_new (_("Ann\303\251e :"));
  gtk_widget_show (label36);
  gtk_fixed_put (GTK_FIXED (fixed6), label36, 488, 264);
  gtk_widget_set_size_request (label36, 49, 17);

  button14 = gtk_button_new ();
  gtk_widget_show (button14);
  gtk_fixed_put (GTK_FIXED (fixed6), button14, 0, 0);
  gtk_widget_set_size_request (button14, 110, 29);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (button14), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image14 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox14), image14, FALSE, FALSE, 0);

  label38 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label38);
  gtk_box_pack_start (GTK_BOX (hbox14), label38, FALSE, FALSE, 0);

  label29 = gtk_label_new (_("<span foreground=\"RED\" ><b> Ajout Fiches donneurs : </b></span>"));
  gtk_widget_show (label29);
  gtk_fixed_put (GTK_FIXED (fixed6), label29, 280, 48);
  gtk_widget_set_size_request (label29, 224, 32);
  gtk_label_set_use_markup (GTK_LABEL (label29), TRUE);

  label33 = gtk_label_new (_("<span ><b> Date de rendez-vous : </b></span>"));
  gtk_widget_show (label33);
  gtk_fixed_put (GTK_FIXED (fixed6), label33, 104, 256);
  gtk_widget_set_size_request (label33, 192, 33);
  gtk_label_set_use_markup (GTK_LABEL (label33), TRUE);

  label31 = gtk_label_new (_("<span ><b> Prenom: </b></span>"));
  gtk_widget_show (label31);
  gtk_fixed_put (GTK_FIXED (fixed6), label31, 112, 160);
  gtk_widget_set_size_request (label31, 80, 17);
  gtk_label_set_use_markup (GTK_LABEL (label31), TRUE);

  label30 = gtk_label_new (_("<span ><b> Nom: </b></span>"));
  gtk_widget_show (label30);
  gtk_fixed_put (GTK_FIXED (fixed6), label30, 120, 112);
  gtk_widget_set_size_request (label30, 49, 17);
  gtk_label_set_use_markup (GTK_LABEL (label30), TRUE);

  label32 = gtk_label_new (_("<span ><b> ID  : </b></span>"));
  gtk_widget_show (label32);
  gtk_fixed_put (GTK_FIXED (fixed6), label32, 112, 208);
  gtk_widget_set_size_request (label32, 49, 17);
  gtk_label_set_use_markup (GTK_LABEL (label32), TRUE);

  label39 = gtk_label_new (_("<span ><b> Type de sang : </b></span>"));
  gtk_widget_show (label39);
  gtk_fixed_put (GTK_FIXED (fixed6), label39, 112, 408);
  gtk_widget_set_size_request (label39, 128, 25);
  gtk_label_set_use_markup (GTK_LABEL (label39), TRUE);

  button15 = gtk_button_new ();
  gtk_widget_show (button15);
  gtk_fixed_put (GTK_FIXED (fixed6), button15, 520, 488);
  gtk_widget_set_size_request (button15, 110, 29);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (button15), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image13 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox13), image13, FALSE, FALSE, 0);

  label37 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label37);
  gtk_box_pack_start (GTK_BOX (hbox13), label37, FALSE, FALSE, 0);

  comboboxentry3 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry3);
  gtk_fixed_put (GTK_FIXED (fixed6), comboboxentry3, 288, 408);
  gtk_widget_set_size_request (comboboxentry3, 189, 29);

  label49 = gtk_label_new (_("<span ><b> Sexe : </b></span>"));
  gtk_widget_show (label49);
  gtk_fixed_put (GTK_FIXED (fixed6), label49, 120, 344);
  gtk_widget_set_size_request (label49, 49, 17);
  gtk_label_set_use_markup (GTK_LABEL (label49), TRUE);

  radiobutton5 = gtk_radio_button_new_with_mnemonic (NULL, _("Homme"));
  gtk_widget_show (radiobutton5);
  gtk_fixed_put (GTK_FIXED (fixed6), radiobutton5, 288, 336);
  gtk_widget_set_size_request (radiobutton5, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton5), radiobutton5_group);
  radiobutton5_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton5));

  radiobutton6 = gtk_radio_button_new_with_mnemonic (NULL, _("Femme "));
  gtk_widget_show (radiobutton6);
  gtk_fixed_put (GTK_FIXED (fixed6), radiobutton6, 288, 360);
  gtk_widget_set_size_request (radiobutton6, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton6), radiobutton5_group);
  radiobutton5_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton6));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ajoutyoussef, ajoutyoussef, "ajoutyoussef");
  GLADE_HOOKUP_OBJECT (ajoutyoussef, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (ajoutyoussef, entry10, "entry10");
  GLADE_HOOKUP_OBJECT (ajoutyoussef, entry11, "entry11");
  GLADE_HOOKUP_OBJECT (ajoutyoussef, entry12, "entry12");
  GLADE_HOOKUP_OBJECT (ajoutyoussef, spinbutton1, "spinbutton1");
  GLADE_HOOKUP_OBJECT (ajoutyoussef, spinbutton2, "spinbutton2");
  GLADE_HOOKUP_OBJECT (ajoutyoussef, spinbutton3, "spinbutton3");
  GLADE_HOOKUP_OBJECT (ajoutyoussef, label34, "label34");
  GLADE_HOOKUP_OBJECT (ajoutyoussef, label35, "label35");
  GLADE_HOOKUP_OBJECT (ajoutyoussef, label36, "label36");
  GLADE_HOOKUP_OBJECT (ajoutyoussef, button14, "button14");
  GLADE_HOOKUP_OBJECT (ajoutyoussef, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (ajoutyoussef, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (ajoutyoussef, image14, "image14");
  GLADE_HOOKUP_OBJECT (ajoutyoussef, label38, "label38");
  GLADE_HOOKUP_OBJECT (ajoutyoussef, label29, "label29");
  GLADE_HOOKUP_OBJECT (ajoutyoussef, label33, "label33");
  GLADE_HOOKUP_OBJECT (ajoutyoussef, label31, "label31");
  GLADE_HOOKUP_OBJECT (ajoutyoussef, label30, "label30");
  GLADE_HOOKUP_OBJECT (ajoutyoussef, label32, "label32");
  GLADE_HOOKUP_OBJECT (ajoutyoussef, label39, "label39");
  GLADE_HOOKUP_OBJECT (ajoutyoussef, button15, "button15");
  GLADE_HOOKUP_OBJECT (ajoutyoussef, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (ajoutyoussef, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (ajoutyoussef, image13, "image13");
  GLADE_HOOKUP_OBJECT (ajoutyoussef, label37, "label37");
  GLADE_HOOKUP_OBJECT (ajoutyoussef, comboboxentry3, "comboboxentry3");
  GLADE_HOOKUP_OBJECT (ajoutyoussef, label49, "label49");
  GLADE_HOOKUP_OBJECT (ajoutyoussef, radiobutton5, "radiobutton5");
  GLADE_HOOKUP_OBJECT (ajoutyoussef, radiobutton6, "radiobutton6");

  return ajoutyoussef;
}

GtkWidget*
create_modifieryoussef (void)
{
  GtkWidget *modifieryoussef;
  GtkWidget *fixed7;
  GtkWidget *label40;
  GtkWidget *entry13;
  GtkWidget *entry14;
  GtkWidget *entry15;
  GtkWidget *label44;
  GtkObject *spinbutton4_adj;
  GtkWidget *spinbutton4;
  GtkObject *spinbutton5_adj;
  GtkWidget *spinbutton5;
  GtkObject *spinbutton6_adj;
  GtkWidget *spinbutton6;
  GtkWidget *label48;
  GtkWidget *label47;
  GtkWidget *label46;
  GtkWidget *label45;
  GtkWidget *comboboxentry4;
  GtkWidget *label43;
  GtkWidget *label42;
  GtkWidget *label41;
  GtkWidget *label50;
  GtkWidget *radiobutton7;
  GSList *radiobutton7_group = NULL;
  GtkWidget *radiobutton8;
  GtkWidget *button17;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image15;
  GtkWidget *label51;
  GtkWidget *button16;
  GtkWidget *alignment16;
  GtkWidget *hbox16;
  GtkWidget *image16;
  GtkWidget *label52;

  modifieryoussef = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (modifieryoussef), _("modifieryoussef"));

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (modifieryoussef), fixed7);
  gtk_widget_set_size_request (fixed7, 800, 600);

  label40 = gtk_label_new (_("<span foreground=\"RED\" ><b> Modifier Fiches donneurs : </b></span>"));
  gtk_widget_show (label40);
  gtk_fixed_put (GTK_FIXED (fixed7), label40, 288, 24);
  gtk_widget_set_size_request (label40, 208, 33);
  gtk_label_set_use_markup (GTK_LABEL (label40), TRUE);

  entry13 = gtk_entry_new ();
  gtk_widget_show (entry13);
  gtk_fixed_put (GTK_FIXED (fixed7), entry13, 288, 104);
  gtk_widget_set_size_request (entry13, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry13), 8226);

  entry14 = gtk_entry_new ();
  gtk_widget_show (entry14);
  gtk_fixed_put (GTK_FIXED (fixed7), entry14, 288, 152);
  gtk_widget_set_size_request (entry14, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry14), 8226);

  entry15 = gtk_entry_new ();
  gtk_widget_show (entry15);
  gtk_fixed_put (GTK_FIXED (fixed7), entry15, 288, 200);
  gtk_widget_set_size_request (entry15, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry15), 8226);

  label44 = gtk_label_new (_("<span ><b> Date naissance : </b></span>"));
  gtk_widget_show (label44);
  gtk_fixed_put (GTK_FIXED (fixed7), label44, 144, 256);
  gtk_widget_set_size_request (label44, 128, 25);
  gtk_label_set_use_markup (GTK_LABEL (label44), TRUE);

  spinbutton4_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton4 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton4_adj), 1, 0);
  gtk_widget_show (spinbutton4);
  gtk_fixed_put (GTK_FIXED (fixed7), spinbutton4, 288, 288);
  gtk_widget_set_size_request (spinbutton4, 60, 27);

  spinbutton5_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton5 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton5_adj), 1, 0);
  gtk_widget_show (spinbutton5);
  gtk_fixed_put (GTK_FIXED (fixed7), spinbutton5, 384, 288);
  gtk_widget_set_size_request (spinbutton5, 60, 27);

  spinbutton6_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton6 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton6_adj), 1, 0);
  gtk_widget_show (spinbutton6);
  gtk_fixed_put (GTK_FIXED (fixed7), spinbutton6, 472, 288);
  gtk_widget_set_size_request (spinbutton6, 60, 27);

  label48 = gtk_label_new (_("Ann\303\251e:"));
  gtk_widget_show (label48);
  gtk_fixed_put (GTK_FIXED (fixed7), label48, 480, 264);
  gtk_widget_set_size_request (label48, 49, 17);

  label47 = gtk_label_new (_("Mois:"));
  gtk_widget_show (label47);
  gtk_fixed_put (GTK_FIXED (fixed7), label47, 392, 264);
  gtk_widget_set_size_request (label47, 49, 17);

  label46 = gtk_label_new (_("Jour:"));
  gtk_widget_show (label46);
  gtk_fixed_put (GTK_FIXED (fixed7), label46, 296, 264);
  gtk_widget_set_size_request (label46, 49, 17);

  label45 = gtk_label_new (_("<span ><b> Type de sang : </b></span>"));
  gtk_widget_show (label45);
  gtk_fixed_put (GTK_FIXED (fixed7), label45, 128, 424);
  gtk_widget_set_size_request (label45, 136, 25);
  gtk_label_set_use_markup (GTK_LABEL (label45), TRUE);

  comboboxentry4 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry4);
  gtk_fixed_put (GTK_FIXED (fixed7), comboboxentry4, 288, 416);
  gtk_widget_set_size_request (comboboxentry4, 189, 29);

  label43 = gtk_label_new (_("<span ><b> ID : </b></span>"));
  gtk_widget_show (label43);
  gtk_fixed_put (GTK_FIXED (fixed7), label43, 136, 200);
  gtk_widget_set_size_request (label43, 49, 17);
  gtk_label_set_use_markup (GTK_LABEL (label43), TRUE);

  label42 = gtk_label_new (_("<span ><b> Prenom: </b></span>"));
  gtk_widget_show (label42);
  gtk_fixed_put (GTK_FIXED (fixed7), label42, 136, 152);
  gtk_widget_set_size_request (label42, 80, 25);
  gtk_label_set_use_markup (GTK_LABEL (label42), TRUE);

  label41 = gtk_label_new (_("<span ><b> Nom: </b></span>"));
  gtk_widget_show (label41);
  gtk_fixed_put (GTK_FIXED (fixed7), label41, 144, 112);
  gtk_widget_set_size_request (label41, 49, 17);
  gtk_label_set_use_markup (GTK_LABEL (label41), TRUE);

  label50 = gtk_label_new (_("<span ><b> Sexe : </b></span>"));
  gtk_widget_show (label50);
  gtk_fixed_put (GTK_FIXED (fixed7), label50, 136, 336);
  gtk_widget_set_size_request (label50, 72, 17);
  gtk_label_set_use_markup (GTK_LABEL (label50), TRUE);

  radiobutton7 = gtk_radio_button_new_with_mnemonic (NULL, _("Homme"));
  gtk_widget_show (radiobutton7);
  gtk_fixed_put (GTK_FIXED (fixed7), radiobutton7, 288, 336);
  gtk_widget_set_size_request (radiobutton7, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton7), radiobutton7_group);
  radiobutton7_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton7));

  radiobutton8 = gtk_radio_button_new_with_mnemonic (NULL, _("Femme"));
  gtk_widget_show (radiobutton8);
  gtk_fixed_put (GTK_FIXED (fixed7), radiobutton8, 288, 368);
  gtk_widget_set_size_request (radiobutton8, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton8), radiobutton7_group);
  radiobutton7_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton8));

  button17 = gtk_button_new ();
  gtk_widget_show (button17);
  gtk_fixed_put (GTK_FIXED (fixed7), button17, 544, 464);
  gtk_widget_set_size_request (button17, 110, 29);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (button17), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image15 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox15), image15, FALSE, FALSE, 0);

  label51 = gtk_label_new_with_mnemonic (_("Confirmer"));
  gtk_widget_show (label51);
  gtk_box_pack_start (GTK_BOX (hbox15), label51, FALSE, FALSE, 0);

  button16 = gtk_button_new ();
  gtk_widget_show (button16);
  gtk_fixed_put (GTK_FIXED (fixed7), button16, 0, 0);
  gtk_widget_set_size_request (button16, 110, 29);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (button16), alignment16);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox16);

  image16 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox16), image16, FALSE, FALSE, 0);

  label52 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label52);
  gtk_box_pack_start (GTK_BOX (hbox16), label52, FALSE, FALSE, 0);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (modifieryoussef, modifieryoussef, "modifieryoussef");
  GLADE_HOOKUP_OBJECT (modifieryoussef, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (modifieryoussef, label40, "label40");
  GLADE_HOOKUP_OBJECT (modifieryoussef, entry13, "entry13");
  GLADE_HOOKUP_OBJECT (modifieryoussef, entry14, "entry14");
  GLADE_HOOKUP_OBJECT (modifieryoussef, entry15, "entry15");
  GLADE_HOOKUP_OBJECT (modifieryoussef, label44, "label44");
  GLADE_HOOKUP_OBJECT (modifieryoussef, spinbutton4, "spinbutton4");
  GLADE_HOOKUP_OBJECT (modifieryoussef, spinbutton5, "spinbutton5");
  GLADE_HOOKUP_OBJECT (modifieryoussef, spinbutton6, "spinbutton6");
  GLADE_HOOKUP_OBJECT (modifieryoussef, label48, "label48");
  GLADE_HOOKUP_OBJECT (modifieryoussef, label47, "label47");
  GLADE_HOOKUP_OBJECT (modifieryoussef, label46, "label46");
  GLADE_HOOKUP_OBJECT (modifieryoussef, label45, "label45");
  GLADE_HOOKUP_OBJECT (modifieryoussef, comboboxentry4, "comboboxentry4");
  GLADE_HOOKUP_OBJECT (modifieryoussef, label43, "label43");
  GLADE_HOOKUP_OBJECT (modifieryoussef, label42, "label42");
  GLADE_HOOKUP_OBJECT (modifieryoussef, label41, "label41");
  GLADE_HOOKUP_OBJECT (modifieryoussef, label50, "label50");
  GLADE_HOOKUP_OBJECT (modifieryoussef, radiobutton7, "radiobutton7");
  GLADE_HOOKUP_OBJECT (modifieryoussef, radiobutton8, "radiobutton8");
  GLADE_HOOKUP_OBJECT (modifieryoussef, button17, "button17");
  GLADE_HOOKUP_OBJECT (modifieryoussef, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (modifieryoussef, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (modifieryoussef, image15, "image15");
  GLADE_HOOKUP_OBJECT (modifieryoussef, label51, "label51");
  GLADE_HOOKUP_OBJECT (modifieryoussef, button16, "button16");
  GLADE_HOOKUP_OBJECT (modifieryoussef, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (modifieryoussef, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (modifieryoussef, image16, "image16");
  GLADE_HOOKUP_OBJECT (modifieryoussef, label52, "label52");

  return modifieryoussef;
}

