/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_nassimwindow (void);
GtkWidget* create_ajoutnassim (void);
GtkWidget* create_modifiernassim (void);
GtkWidget* create_supprimerwindow (void);
GtkWidget* create_youssefwindow (void);
GtkWidget* create_ajoutyoussef (void);
GtkWidget* create_modifieryoussef (void);
